spring.application.name=pms
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

finnhub.api.key=${FINNHUB_API_KEY}


app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000