INSERT IGNORE INTO stock (symbol, company_name, industry, sector)
VALUES
    ('AAPL',  'Apple Inc.',                             'Computers/Consumer Electronics',      'Technology'),
    ('MSFT',  'Microsoft Corp.',                        'Software',                            'Technology'),
    ('GOOGL', 'Alphabet Inc. Cl A',                     'Internet/Online',                     'Technology'),
    ('AMZN',  'Amazon.com Inc.',                        'Mixed Retailing',                     'Retail/Wholesale'),
    ('NVDA',  'NVIDIA Corp.',                           'Semiconductors',                      'Technology'),
    ('META',  'Meta Platforms Inc.',                    'Internet/Online',                     'Technology'),
    ('TSLA',  'Tesla Inc.',                             'Automobiles',                         'Automotive'),
    ('BRK.B', 'Berkshire Hathaway Inc. Cl B',           'Diversified Holding Companies',       'Business/Consumer Services'),
    ('JPM',   'JPMorgan Chase & Co.',                   'Major International Banks',           'Financial Services'),
    ('V',     'Visa Inc. Cl A',                         'Consumer Finance',                    'Financial Services'),
    ('UNH',   'UnitedHealth Group Inc.',                'Life Insurance',                      'Financial Services'),
    ('XOM',   'Exxon Mobil Corp.',                      'Major Oil & Natural Gas Companies',   'Energy'),
    ('MA',    'Mastercard Inc.',                        'Consumer Finance',                    'Financial Services'),
    ('JNJ',   'Johnson & Johnson',                      'Pharmaceuticals',                     'Health Care/Life Sciences'),
    ('PG',    'Procter & Gamble Co.',                   'Personal Care Products/Appliances',   'Consumer Goods'),
    ('HD',    'Home Depot Inc.',                        'Home Goods Retail',                   'Retail/Wholesale'),
    ('COST',  'Costco Wholesale Corp.',                 'Mixed Retailing',                     'Retail/Wholesale'),
    ('ABBV',  'AbbVie Inc.',                            'Biotechnology',                       'Health Care/Life Sciences'),
    ('CRM',   'Salesforce Inc.',                        'Software',                            'Technology'),
    ('BAC',   'Bank of America Corp.',                  'Major International Banks',           'Financial Services'),
    ('AVGO',  'Broadcom Inc.',                          'Semiconductors',                      'Technology'),
    ('KO',    'Coca-Cola Co.',                          'Non-Alcoholic Beverages/Drinks',      'Consumer Goods'),
    ('WMT',   'Walmart Inc.',                           'Mixed Retailing',                     'Retail/Wholesale'),
    ('PEP',   'PepsiCo Inc.',                           'Non-Alcoholic Beverages/Drinks',      'Consumer Goods'),
    ('MRK',   'Merck & Co. Inc.',                       'Pharmaceuticals',                     'Health Care/Life Sciences'),
    ('LLY',   'Eli Lilly & Co.',                        'Pharmaceuticals',                     'Health Care/Life Sciences'),
    ('TMO',   'Thermo Fisher Scientific Inc.',          'Medical Equipment/Supplies',          'Health Care/Life Sciences'),
    ('CSCO',  'Cisco Systems Inc.',                     'Networking',                          'Technology'),
    ('ADBE',  'Adobe Inc.',                             'Software',                            'Technology'),
    ('NFLX',  'Netflix Inc.',                           'Broadcasting',                        'Media/Entertainment');